### ISSUE TITLE
Make it clear in abstract that public presentations shouldn't be heavily relied on

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/linked-vp#14]
We should make it clear that public VPs should be rare and not relied on too heavily. We should link to the other protocols.

**Comment by brianorwhatever** [comment]
Can't assign myself 🙁

**Comment by jceb** [comment]
@brianorwhatever is there anything you'd like to add to the existing state of the spec concerning this issue?

**Comment by brianorwhatever** [comment]
@jceb I added a PR with a sentence. After thinking more on it though I am ok if we don't want this disclaimer, leaving it to implementers to do the right thing 😄
