### ISSUE TITLE
Deploy to a permanent URL

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/linked-vp#30]
We need a DIF spec url for this spec.

**Comment by peacekeeper** [comment]
+1, I will take care of this.

**Comment by peacekeeper** [comment]
So basically the index.html file at the root of this repo:
https://github.com/decentralized-identity/linked-vp

Should be exposed at a static URL like this:
https://identity.foundation/linked-vp/

The DIF website is currently undergoing a migration process, maybe we have to wait a bit until that is completed.

**Comment by peacekeeper** [comment]
@Pratap2018 FYI

**Comment by jceb** [comment]
Is there anything else to be done? The task looks finished to me.

**Comment by peacekeeper** [comment]
I agree, this seems done, closing.
