### ISSUE TITLE
Consider contributor guidelines

### ISSUE THREAD

**Issue by peacekeeper** [decentralized-identity/linked-vp#31]
According to the work item lifecycle:
https://github.com/decentralized-identity/org/blob/master/work-item-lifecycle.md#72-draft

> Work items or their groups MAY customize the standard contributor guidelines template.

Let's find out if this work item should do anything to customize the contributor guidelines.

**Comment by jceb** [comment]
We included the working group in the acknowledgements section. Nothing else required here.
